name = "TI_Schrod"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "jane.doe@example.com"
copyright = "Copyright 2022, Jane Doe"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[library]
source-dir="src"

[[ executable ]]
name="TI_Schrod"
source-dir="app"
main="TI_Schrod.f90"
