name = "TI_Schrod"
version = "0.1.0"
license = "license"
author = "Robert AFANSOUNOUDJI"
maintainer = "afankokourobrt@gmail.com"
copyright = "Copyright 2022, Robert AFANSOUNOUDJI"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
link = ["blas", "lapack","arpack2-dev"]

[install]
library = false

[library]
source-dir="src"

[[ executable ]]
name="TI_Schrod"
source-dir="app"
main="TI_Schrod.f90"
