name = "TI_Schrod"
version = "0.1.0"
license = "license"
author = "AFANSOUNOUDJI Robert"
maintainer = "afankokourobert@gmail.com"
copyright = "Copyright 2022, AFANSOUNOUDJI Robert"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
link = ["blas", "lapack"]

[install]
library = false

[library]
source-dir="src"

[[ executable ]]
name="TI_Schrod"
source-dir="app"
main="TI_Schrod.f90"
